# Generated by Django 3.0.4 on 2020-05-07 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
