# Generated by Django 3.0.4 on 2020-05-07 15:44

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20200507_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='title', unique_with=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Category')),
        ),
    ]
