# Generated by Django 3.0.4 on 2020-05-07 15:46

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20200507_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='title', unique_with=models.CharField(blank=True, max_length=250)),
        ),
    ]
