# Generated by Django 3.0.4 on 2020-05-07 16:16

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20200507_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slugDescription',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='description', unique_with=('created_at',)),
        ),
        migrations.AlterField(
            model_name='product',
            name='slugTitle',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='title', unique_with=('created_at',)),
        ),
    ]
