# Generated by Django 3.0.4 on 2020-05-07 16:19

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_product_slugcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slugDescription',
        ),
        migrations.AlterField(
            model_name='product',
            name='slugCategory',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='category', unique_with=('created_at',)),
        ),
        migrations.AlterField(
            model_name='product',
            name='slugTitle',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique_with=('created_at',)),
        ),
    ]
