# Generated by Django 3.0.4 on 2020-05-09 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_images_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='category',
            field=models.ForeignKey(default='NULL', on_delete=django.db.models.deletion.CASCADE, to='product.Category'),
        ),
    ]
