# Generated by Django 3.0.4 on 2020-05-09 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_auto_20200509_0425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='category',
        ),
    ]
