# Generated by Django 3.0.4 on 2020-05-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_auto_20200509_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='No Picture', upload_to='CategoryImages/'),
        ),
    ]
