# Generated by Django 3.0.4 on 2020-05-09 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_auto_20200510_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='CategoryImages/'),
        ),
    ]
