# Generated by Django 3.0.4 on 2020-05-10 15:39

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_auto_20200510_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slugCategory',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='category'),
        ),
    ]
