# Generated by Django 3.0.4 on 2020-05-09 11:45

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200330_2003'),
    ]

    operations = [

    ]
