# Generated by Django 3.0.4 on 2020-05-09 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200509_1448'),
        ('home', '0004_auto_20200507_1643'),
    ]

    operations = [
    ]
