# Generated by Django 3.0.4 on 2020-06-18 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200605_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tableno',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
